name: passing data between steps

on:
  workflow_dispatch:

jobs:
  data-passing:
    runs-on: ubuntu-latest
    
    steps:
      - name: create data
        id: sender
        run: |
           echo "name=bruce" >> $GITHUB_OUTPUT
      - name: receive data
        run: |
           echo ${{ steps.sender.outputs.name }}
