name: 08 Secrets and variables

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    env:
      DEPLOYMENT_ENV: 'production'

    steps:
      - name: build
        run: |
          echo ${{ secrets.API_KEY }}
          echo ${{ vars.USERNAME }}
          echo ${{ env.DEPLOYMENT_ENV }}
        
        env:
          SECRETS_API_KEY: ${{ secrets.API_KEY }}
          STEPS_USERNAME: ${{ vars.username }}
          CONFIG_VARIABLE: ${{ env.DEPLOYMENT_ENV}}
          
      - name: deploy
        run: |
          echo "global job variable ${{ env.DEPLOYMENT_ENV  }}"
          echo "Variable from the previous step {$CONFIG_VARIABLE} environment"
          echo "variable from this step ${{ secrets.API_KEY }}"
          echo "local step variable ${ ANOTHER_VARIABLE }"

        env:
          SECRETS_API_KEY: ${{ secrets.API_KEY }}
          CONFIG_VARIABLE2: ${{ env.DEPLOYMENT_ENV }}
          ANOTHER_VARIABLE: 'some value'