name: 12 PAT Bump tag
on:
  pull_request:
    types:
      - closed
    branches:
      main

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 #always check from the main branch
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }} # to get the code from the specific  commit from the recent pr
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        WITH_V: true  